spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jl-center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDetele # 逻辑删除
      logic-delete-value: 1 # 逻辑已删除
      logic-not-delete-value: 0 # 逻辑为删除
