spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jl-center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
